SELECT
	A.CL_CODE,
    A.CL_CODE_NM,
    B.CODE_ID,
    B.CODE_ID_NM,
    C.CODE,
    C.CODE_NM,
    C.CODE_DC_EN
FROM TC_CMMNCODE_CL A, TC_CMMNCODE_CTGRY B, TC_CMMNCODE_DETAIL C
WHERE A.CL_CODE = B.CL_CODE
AND B.CODE_ID = C.CODE_ID
AND A.USE_AT = 'Y' AND B.USE_AT='Y' AND C.USE_AT ='Y'
AND A.CL_CODE <> 'EFC'
ORDER BY A.CL_CODE_NM, CODE_ID_NM , CODE_NM

