CREATE TABLE COMTNBBSMASTER (
  BBS_ID                    VARCHAR2(20)       NOT NULL,
  BBS_TY_CODE               VARCHAR2(7)        NOT NULL,
  LAST_UPDUSR_PNTTM         DATE,
  USE_AT                    CHAR(1)            NOT NULL,
  FRST_REGISTER_PNTTM       DATE               NOT NULL,
  FRST_REGISTER_ID          VARCHAR2(20)       NOT NULL,
  LAST_UPDUSR_ID            VARCHAR2(20),
  BBS_ATTRB_CODE            VARCHAR2(7)        NOT NULL,
  BBS_NM                    VARCHAR2(120)      NOT NULL,
  REPLY_POSBL_AT            CHAR(1),
  FILE_ATCH_POSBL_AT        CHAR(1)            NOT NULL,
  POSBL_ATCH_FILE_NUMBER    NUMBER(2)          NOT NULL,
  POSBL_ATCH_FILE_SIZE      VARCHAR2(8),
  BBS_INTRCN                VARCHAR2(2400),
  TMPLAT_ID                 CHAR(20),
  COMM_POSBL_AT             CHAR(1),
  DELCODE                   CHAR(1)           DEFAULT '0',
  ADD_CON                   VARCHAR2(4000),
  CMMNT_POSBL_AT            CHAR(1),
  NTCE_BGNDE                VARCHAR2(10),
  NTCE_ENDDE                VARCHAR2(10),
  PAGE_SIZE                 NUMBER,
  PAGE_UNIT                 NUMBER,
  PREV_NEXT_POSBL_AT        CHAR(1),
  TABLE_NM                  VARCHAR2(64),
    CONSTRAINT COMTNBBSMASTER_PK
    PRIMARY KEY ( BBS_ID )
);

COMMENT ON TABLE COMTNBBSMASTER IS '게시판마스터[게시판 정보관리(게시판속성) ]';

COMMENT ON COLUMN COMTNBBSMASTER.BBS_ID IS '게시판ID';

COMMENT ON COLUMN COMTNBBSMASTER.BBS_TY_CODE IS '게시판유형코드';

COMMENT ON COLUMN COMTNBBSMASTER.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTNBBSMASTER.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTNBBSMASTER.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTNBBSMASTER.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTNBBSMASTER.LAST_UPDUSR_ID IS '최종수정자ID';

COMMENT ON COLUMN COMTNBBSMASTER.BBS_ATTRB_CODE IS '게시판속성코드';

COMMENT ON COLUMN COMTNBBSMASTER.BBS_NM IS '게시판명';

COMMENT ON COLUMN COMTNBBSMASTER.REPLY_POSBL_AT IS '답글가능여부';

COMMENT ON COLUMN COMTNBBSMASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부';

COMMENT ON COLUMN COMTNBBSMASTER.POSBL_ATCH_FILE_NUMBER IS '첨부가능파일숫자';

COMMENT ON COLUMN COMTNBBSMASTER.POSBL_ATCH_FILE_SIZE IS '첨부가능파일사이즈';

COMMENT ON COLUMN COMTNBBSMASTER.BBS_INTRCN IS '게시판소개';

COMMENT ON COLUMN COMTNBBSMASTER.TMPLAT_ID IS '템플릿ID';

COMMENT ON COLUMN COMTNBBSMASTER.COMM_POSBL_AT IS '댓글가능여부';

COMMENT ON COLUMN COMTNBBSMASTER.DELCODE IS '삭제여부
[ 0=미삭제 | 1=삭제 ]';

COMMENT ON COLUMN COMTNBBSMASTER.ADD_CON IS '추가컨텐츠';

COMMENT ON COLUMN COMTNBBSMASTER.CMMNT_POSBL_AT IS '커멘트가능여';

COMMENT ON COLUMN COMTNBBSMASTER.NTCE_BGNDE IS '게시물시작일';

COMMENT ON COLUMN COMTNBBSMASTER.NTCE_ENDDE IS '게시물종료일';

COMMENT ON COLUMN COMTNBBSMASTER.PAGE_SIZE IS '페이지크기';

COMMENT ON COLUMN COMTNBBSMASTER.PAGE_UNIT IS '페이지유닛';

COMMENT ON COLUMN COMTNBBSMASTER.PREV_NEXT_POSBL_AT IS '이전글다음글사용여부';

COMMENT ON COLUMN COMTNBBSMASTER.TABLE_NM IS '테이블명';

CREATE TABLE COMTNBBS_BASIC (
  NTT_ID                 NUMBER(20)         NOT NULL,
  BBS_ID                 VARCHAR2(20)       NOT NULL,
  NTCR_ID                VARCHAR2(100),
  SORT_ORDR              NUMBER(8),
  NTCR_NM                VARCHAR2(50),
  PASSWORD               VARCHAR2(2000),
  NTT_SJ                 VARCHAR2(3000)     NOT NULL,
  NTT_CN                 CLOB,
  INQIRE_CO              NUMBER(9)         DEFAULT 0,
  USE_AT                 CHAR(1)            NOT NULL,
  NTCE_BGNDE             CHAR(10),
  NTCE_ENDDE             CHAR(10),
  FRST_REGISTER_PNTTM    DATE               NOT NULL,
  LAST_UPDUSR_PNTTM      DATE,
  FRST_REGISTER_ID       VARCHAR2(100),
  LAST_UPDUSR_ID         VARCHAR2(100),
  REPLY_AT               CHAR(1),
  PARNTS                 NUMBER(10),
  NTT_NO                 NUMBER(10),
  REPLY_LC               NUMBER(8),
  ATCH_FILE_ID           CHAR(20),
  DELCODE                CHAR(1),
  SECRET                 CHAR(1),
  NTT_TYPE               NUMBER,
  HTML_YN                CHAR(1),
  DEPT_NAME              VARCHAR2(500),
  DEPT_ID                VARCHAR2(100),
  GUBUN                  VARCHAR2(10),
    PRIMARY KEY ( NTT_ID ),
    FOREIGN KEY ( BBS_ID )
        REFERENCES COMTNBBSMASTER ( BBS_ID )
)
;

COMMENT ON TABLE COMTNBBS_BASIC IS '통합게시판 정보';

COMMENT ON COLUMN COMTNBBS_BASIC.NTT_ID IS '게시물ID';

COMMENT ON COLUMN COMTNBBS_BASIC.BBS_ID IS '게시판ID';

COMMENT ON COLUMN COMTNBBS_BASIC.NTCR_ID IS '게시자ID';

COMMENT ON COLUMN COMTNBBS_BASIC.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN COMTNBBS_BASIC.NTCR_NM IS '게시자명';

COMMENT ON COLUMN COMTNBBS_BASIC.PASSWORD IS '패스워드';

COMMENT ON COLUMN COMTNBBS_BASIC.NTT_SJ IS '게시물제목';

COMMENT ON COLUMN COMTNBBS_BASIC.NTT_CN IS '게시물내용';

COMMENT ON COLUMN COMTNBBS_BASIC.INQIRE_CO IS '조회횟수';

COMMENT ON COLUMN COMTNBBS_BASIC.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTNBBS_BASIC.NTCE_BGNDE IS '게시시작일';

COMMENT ON COLUMN COMTNBBS_BASIC.NTCE_ENDDE IS '게시종료일';

COMMENT ON COLUMN COMTNBBS_BASIC.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTNBBS_BASIC.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTNBBS_BASIC.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTNBBS_BASIC.LAST_UPDUSR_ID IS '최종수정자ID';

COMMENT ON COLUMN COMTNBBS_BASIC.REPLY_AT IS '답글여부';

COMMENT ON COLUMN COMTNBBS_BASIC.PARNTS IS '부모글번호';

COMMENT ON COLUMN COMTNBBS_BASIC.NTT_NO IS '게시물번호';

COMMENT ON COLUMN COMTNBBS_BASIC.REPLY_LC IS '답글위치';

COMMENT ON COLUMN COMTNBBS_BASIC.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN COMTNBBS_BASIC.DELCODE IS '삭제여부
[ 0=미삭제 | 1=삭제 ]';

COMMENT ON COLUMN COMTNBBS_BASIC.SECRET IS '비밀글여부
[ Y=비밀글 | N=아님 ]';

COMMENT ON COLUMN COMTNBBS_BASIC.NTT_TYPE IS '공지글여부.';

COMMENT ON COLUMN COMTNBBS_BASIC.HTML_YN IS 'HTML여부.';

COMMENT ON COLUMN COMTNBBS_BASIC.DEPT_NAME IS '담당부서명.';

COMMENT ON COLUMN COMTNBBS_BASIC.DEPT_ID IS '부서아이디.';

COMMENT ON COLUMN COMTNBBS_BASIC.GUBUN IS '게시판 구분';

CREATE INDEX FRST_REGISTER_PNTTM_DESC
ON COMTNBBS_BASIC (FRST_REGISTER_PNTTM)
LOGGING
NOPARALLEL;

CREATE TABLE COMTNBBS (
  NTT_ID                 NUMBER(20)         NOT NULL,
  BBS_ID                 VARCHAR2(20)       NOT NULL,
  NTCR_ID                VARCHAR2(20),
  SORT_ORDR              NUMBER(8),
  NTCR_NM                VARCHAR2(50),
  NTCR_EMAIL             VARCHAR2(100),
  NTCR_PINNO             VARCHAR2(70),
  NTCR_ZIPCODE           VARCHAR2(7),
  NTCR_ADDR1             VARCHAR2(50),
  NTCR_ADDR2             VARCHAR2(50),
  NTCR_TEL               VARCHAR2(14),
  NTCR_HP                VARCHAR2(14),
  PASSWORD               VARCHAR2(2000),
  NTT_SJ                 VARCHAR2(2400),
  NTT_CN                 CLOB,
  INQIRE_CO              NUMBER(9),
  USE_AT                 CHAR(1)            NOT NULL,
  NTCE_BGNDE             VARCHAR2(10),
  NTCE_ENDDE             VARCHAR2(10),
  FRST_REGISTER_PNTTM    DATE               NOT NULL,
  LAST_UPDUSR_PNTTM      DATE,
  FRST_REGISTER_ID       VARCHAR2(20),
  LAST_UPDUSR_ID         VARCHAR2(20),
  REPLY_AT               CHAR(1),
  PARNTS                 NUMBER(10),
  NTT_NO                 NUMBER(10),
  REPLY_LC               NUMBER(8),
  ATCH_FILE_ID           CHAR(20),
  DELCODE                CHAR(1),
  SECRET                 CHAR(1),
  OPTION1                VARCHAR2(4000),
  OPTION2                VARCHAR2(4000),
  OPTION3                VARCHAR2(4000),
  OPTION4                VARCHAR2(4000),
  OPTION5                VARCHAR2(4000),
  OPTION6                VARCHAR2(4000),
  OPTION7                VARCHAR2(4000),
  OPTION8                VARCHAR2(4000),
  OPTION9                VARCHAR2(4000),
  OPTION10               VARCHAR2(4000),
  NTT_TYPE               NUMBER(2),
  DEPT_ID                VARCHAR2(15),
  OPTION11               VARCHAR2(4000),
  OPTION12               VARCHAR2(4000),
  OPTION13               VARCHAR2(4000),
  OPTION14               VARCHAR2(4000),
  OPTION15               VARCHAR2(4000),
  OPTION16               VARCHAR2(4000),
  OPTION17               VARCHAR2(4000),
  OPTION18               VARCHAR2(4000),
  OPTION19               VARCHAR2(4000),
  OPTION20               VARCHAR2(4000),
  HTML_YN                CHAR(1),
  GUBUN                  VARCHAR2(100),
    CONSTRAINT PK_COMTNBBS
    PRIMARY KEY ( NTT_ID, BBS_ID )
)
;

COMMENT ON TABLE COMTNBBS IS '게시판';

COMMENT ON COLUMN COMTNBBS.OPTION1 IS '옵션1';

COMMENT ON COLUMN COMTNBBS.OPTION2 IS '옵션2';

COMMENT ON COLUMN COMTNBBS.OPTION3 IS '옵션3';

COMMENT ON COLUMN COMTNBBS.OPTION4 IS '옵션4';

COMMENT ON COLUMN COMTNBBS.OPTION5 IS '옵션5';

COMMENT ON COLUMN COMTNBBS.OPTION6 IS '옵션6';

COMMENT ON COLUMN COMTNBBS.OPTION7 IS '옵션7';

COMMENT ON COLUMN COMTNBBS.OPTION8 IS '옵션8';

COMMENT ON COLUMN COMTNBBS.OPTION9 IS '옵션9';

COMMENT ON COLUMN COMTNBBS.OPTION10 IS '옵션10';

COMMENT ON COLUMN COMTNBBS.NTT_TYPE IS '게시글형태[1=공지,2=일반]';

COMMENT ON COLUMN COMTNBBS.DEPT_ID IS '부서아이디';

COMMENT ON COLUMN COMTNBBS.OPTION11 IS '옵션11';

COMMENT ON COLUMN COMTNBBS.OPTION12 IS '옵션12';

COMMENT ON COLUMN COMTNBBS.OPTION13 IS '옵션13';

COMMENT ON COLUMN COMTNBBS.OPTION14 IS '옵션14';

COMMENT ON COLUMN COMTNBBS.OPTION15 IS '옵션15';

COMMENT ON COLUMN COMTNBBS.OPTION16 IS '옵션16';

COMMENT ON COLUMN COMTNBBS.OPTION17 IS '옵션17';

COMMENT ON COLUMN COMTNBBS.OPTION18 IS '옵션18';

COMMENT ON COLUMN COMTNBBS.OPTION19 IS '옵션19';

COMMENT ON COLUMN COMTNBBS.OPTION20 IS '옵션20';

COMMENT ON COLUMN COMTNBBS.NTT_ID IS '게시물ID';

COMMENT ON COLUMN COMTNBBS.BBS_ID IS '게시판ID';

COMMENT ON COLUMN COMTNBBS.NTCR_ID IS '게시자ID';

COMMENT ON COLUMN COMTNBBS.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN COMTNBBS.NTCR_NM IS '게시자명';

COMMENT ON COLUMN COMTNBBS.NTCR_EMAIL IS '이메일';

COMMENT ON COLUMN COMTNBBS.NTCR_PINNO IS '핀번호';

COMMENT ON COLUMN COMTNBBS.NTCR_ZIPCODE IS '우편번호';

COMMENT ON COLUMN COMTNBBS.NTCR_ADDR1 IS '주소';

COMMENT ON COLUMN COMTNBBS.NTCR_ADDR2 IS '상세주소';

COMMENT ON COLUMN COMTNBBS.NTCR_TEL IS '집전화번호';

COMMENT ON COLUMN COMTNBBS.NTCR_HP IS '핸드폰번호';

COMMENT ON COLUMN COMTNBBS.PASSWORD IS '패스워드';

COMMENT ON COLUMN COMTNBBS.NTT_SJ IS '게시물제목';

COMMENT ON COLUMN COMTNBBS.NTT_CN IS '게시물내용';

COMMENT ON COLUMN COMTNBBS.INQIRE_CO IS '조회횟수';

COMMENT ON COLUMN COMTNBBS.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTNBBS.NTCE_BGNDE IS '게시시작일';

COMMENT ON COLUMN COMTNBBS.NTCE_ENDDE IS '게시종료일';

COMMENT ON COLUMN COMTNBBS.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTNBBS.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTNBBS.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTNBBS.LAST_UPDUSR_ID IS '최종수정자ID';

COMMENT ON COLUMN COMTNBBS.REPLY_AT IS '답글여부';

COMMENT ON COLUMN COMTNBBS.PARNTS IS '부모글번호';

COMMENT ON COLUMN COMTNBBS.NTT_NO IS '게시물번호';

COMMENT ON COLUMN COMTNBBS.REPLY_LC IS '답글위치';

COMMENT ON COLUMN COMTNBBS.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN COMTNBBS.DELCODE IS '삭제여부';

COMMENT ON COLUMN COMTNBBS.SECRET IS '비밀글여부';

COMMENT ON COLUMN COMTNBBS.HTML_YN IS 'HTML여부';

COMMENT ON COLUMN COMTNBBS.GUBUN IS '구분';

CREATE TABLE COMTNMENUINFO (
  MENU_NM           VARCHAR2(256)      NOT NULL,
  MENU_NO           NUMBER(20)         NOT NULL,
  UPPER_MENU_NO     NUMBER(20)         NOT NULL,
  MENU_ORDR         NUMBER(20)         NOT NULL,
  MENU_DC           VARCHAR2(2000),
  SITE_ID           NUMBER(2)          NOT NULL,
  MENU_LINK         VARCHAR2(255),
  MENU_POPUP_YN     CHAR(1),
  DEPT_ID           VARCHAR2(20),
  PATH              VARCHAR2(1000),
  FULL_PATH         VARCHAR2(2000),
  FULL_MENU_LINK    VARCHAR2(400),
  CONTENTS_PATH     VARCHAR2(400),
  USE_YN            CHAR(1)            NOT NULL,
  MODIFY_DAY        DATE              DEFAULT SYSDATE,
  POSITION          VARCHAR2(64),
  LEAF_NODE_YN      CHAR(1),
  USER_ID           VARCHAR2(100),
  BBS_ID            VARCHAR2(20),
    CONSTRAINT PK_COMTNMENUINFO
    PRIMARY KEY ( MENU_NO )
)
;

COMMENT ON TABLE COMTNMENUINFO IS '메뉴정보';

COMMENT ON COLUMN COMTNMENUINFO.MENU_NM IS '메뉴한글명';

COMMENT ON COLUMN COMTNMENUINFO.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN COMTNMENUINFO.UPPER_MENU_NO IS '상위메뉴번호';

COMMENT ON COLUMN COMTNMENUINFO.MENU_ORDR IS '메뉴순서';

COMMENT ON COLUMN COMTNMENUINFO.MENU_DC IS '메뉴설명';

COMMENT ON COLUMN COMTNMENUINFO.SITE_ID IS '사이트ID';

COMMENT ON COLUMN COMTNMENUINFO.MENU_LINK IS '메뉴링크';

COMMENT ON COLUMN COMTNMENUINFO.MENU_POPUP_YN IS '팝업사용유무';

COMMENT ON COLUMN COMTNMENUINFO.DEPT_ID IS '부서ID';

COMMENT ON COLUMN COMTNMENUINFO.PATH IS '파일경로';

COMMENT ON COLUMN COMTNMENUINFO.FULL_PATH IS '전체파일경로';

COMMENT ON COLUMN COMTNMENUINFO.FULL_MENU_LINK IS '전체 링크 경로';

COMMENT ON COLUMN COMTNMENUINFO.CONTENTS_PATH IS '콘텐츠 path(파일관리시)';

COMMENT ON COLUMN COMTNMENUINFO.USE_YN IS '사용여부';

COMMENT ON COLUMN COMTNMENUINFO.MODIFY_DAY IS '수정일';

COMMENT ON COLUMN COMTNMENUINFO.POSITION IS '위치';

COMMENT ON COLUMN COMTNMENUINFO.LEAF_NODE_YN IS '리프노드유무';

COMMENT ON COLUMN COMTNMENUINFO.USER_ID IS '담당자아이디';

COMMENT ON COLUMN COMTNMENUINFO.BBS_ID IS '게시판아이디';

CREATE TABLE COMTNFILE (
  ATCH_FILE_ID    CHAR(20)     NOT NULL,
  CREAT_DT        DATE         NOT NULL,
  USE_AT          CHAR(1)      NOT NULL,
    CONSTRAINT COMTNFILE_PK
    PRIMARY KEY ( ATCH_FILE_ID )
)
;

COMMENT ON TABLE COMTNFILE IS '파일속성';

COMMENT ON COLUMN COMTNFILE.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN COMTNFILE.CREAT_DT IS '생성일시';

COMMENT ON COLUMN COMTNFILE.USE_AT IS '사용여부';

CREATE TABLE COMTNFILEDETAIL (
  ATCH_FILE_ID       CHAR(20)           NOT NULL,
  FILE_SN            NUMBER(4)          NOT NULL,
  FILE_STRE_COURS    VARCHAR2(2000)     NOT NULL,
  STRE_FILE_NM       VARCHAR2(255)      NOT NULL,
  ORIGNL_FILE_NM     VARCHAR2(255),
  FILE_EXTSN         VARCHAR2(20),
  FILE_MG            NUMBER(12),
  FILE_CN            CLOB,
  FILE_WD            VARCHAR2(10),
  FILE_FIELD_NAME    VARCHAR2(50),
    CONSTRAINT COMTNFILEDETAIL_PK
    PRIMARY KEY ( ATCH_FILE_ID, FILE_SN ),
    FOREIGN KEY ( ATCH_FILE_ID )
        REFERENCES COMTNFILE ( ATCH_FILE_ID )
)
;

COMMENT ON TABLE COMTNFILEDETAIL IS '파일상세정보';

COMMENT ON COLUMN COMTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_SN IS '파일연번';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로';

COMMENT ON COLUMN COMTNFILEDETAIL.STRE_FILE_NM IS '저장파일명';

COMMENT ON COLUMN COMTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_EXTSN IS '파일확장자';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_MG IS '파일크기';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_CN IS '파일내용';

COMMENT ON COLUMN COMTNFILEDETAIL.FILE_FIELD_NAME IS '파일필드명';

CREATE TABLE SITE_MNG (
  SITE_ID      NUMBER(3)         NOT NULL,
  SITE_NAME    VARCHAR2(30)      NOT NULL,
  SITE_DESC    VARCHAR2(800),
  SITE_URL     VARCHAR2(255)     NOT NULL,
  CREAT_DT     DATE             DEFAULT SYSDATE,
    PRIMARY KEY ( SITE_ID )
)
;

COMMENT ON TABLE SITE_MNG IS '사이트정의';

COMMENT ON COLUMN SITE_MNG.SITE_ID IS '사이트아이디';

COMMENT ON COLUMN SITE_MNG.SITE_NAME IS '사이트이름';

COMMENT ON COLUMN SITE_MNG.SITE_DESC IS '사이트한글명';

COMMENT ON COLUMN SITE_MNG.SITE_URL IS '주소';

COMMENT ON COLUMN SITE_MNG.CREAT_DT IS '생성일시';

CREATE TABLE PAGE_ATTR (
  PAGE_CODE    VARCHAR2(20)       NOT NULL,
  PAGE_DESC    VARCHAR2(2400),
  PAGE_NAME    VARCHAR2(120)      NOT NULL,
  CREAT_DT     DATE               NOT NULL,
    CONSTRAINT PK_PAGE_ATTR
    PRIMARY KEY ( PAGE_CODE )
)
;

COMMENT ON TABLE PAGE_ATTR IS '게시판속성';

COMMENT ON COLUMN PAGE_ATTR.PAGE_CODE IS '게시판속성코드';

COMMENT ON COLUMN PAGE_ATTR.PAGE_DESC IS '게시판속성상세';

COMMENT ON COLUMN PAGE_ATTR.PAGE_NAME IS '게시판속성명';

COMMENT ON COLUMN PAGE_ATTR.CREAT_DT IS '등록일시';

CREATE TABLE PAGE_FIELD_ATTR (
  FIELD_ID      NUMBER            NOT NULL,
  PAGE_CODE     VARCHAR2(20)      NOT NULL,
  PAGE_TYPE     VARCHAR2(20)      NOT NULL,
  FIELD_NAME    VARCHAR2(120)     NOT NULL,
  FIELD_TYPE    VARCHAR2(8)       NOT NULL,
  FIELD_TEXT    VARCHAR2(120)     NOT NULL,
  FIELD_ORDR    NUMBER,
  FIELD_LIST    CHAR(1)          DEFAULT 'N',
    CONSTRAINT PK_PAGE_FIELD_ATTR
    PRIMARY KEY ( FIELD_ID ),
    FOREIGN KEY ( PAGE_CODE )
        REFERENCES PAGE_ATTR ( PAGE_CODE )
)
;

COMMENT ON TABLE PAGE_FIELD_ATTR IS '필드정보';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_ID IS '필드아이디';

COMMENT ON COLUMN PAGE_FIELD_ATTR.PAGE_CODE IS '페이지코드';

COMMENT ON COLUMN PAGE_FIELD_ATTR.PAGE_TYPE IS '페이지타입';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_NAME IS '필드이름';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_TYPE IS '필드타입';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_TEXT IS '필드한글이름';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_ORDR IS '필드순서';

COMMENT ON COLUMN PAGE_FIELD_ATTR.FIELD_LIST IS '리스트노출';

CREATE TABLE COMTCCMMNCLCODE (
  CL_CODE                VARCHAR2(4)       NOT NULL,
  CL_CODE_NM             VARCHAR2(240),
  CL_CODE_DC             VARCHAR2(800),
  USE_AT                 CHAR(1),
  FRST_REGISTER_PNTTM    DATE             DEFAULT sysdate,
  FRST_REGISTER_ID       VARCHAR2(20),
  LAST_UPDUSR_PNTTM      DATE             DEFAULT sysdate,
  LAST_UPDUSR_ID         VARCHAR2(20),
    CONSTRAINT COMTCCMMNCLCODE_PK
    PRIMARY KEY ( CL_CODE )
)
;

COMMENT ON TABLE COMTCCMMNCLCODE IS '공통코드 분류 관리';

COMMENT ON COLUMN COMTCCMMNCLCODE.CL_CODE IS '분류코드';

COMMENT ON COLUMN COMTCCMMNCLCODE.CL_CODE_NM IS '분류코드명';

COMMENT ON COLUMN COMTCCMMNCLCODE.CL_CODE_DC IS '분류코드 설명';

COMMENT ON COLUMN COMTCCMMNCLCODE.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTCCMMNCLCODE.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTCCMMNCLCODE.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTCCMMNCLCODE.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTCCMMNCLCODE.LAST_UPDUSR_ID IS '최종수정자ID';

CREATE TABLE COMTCCMMNCODE (
  CL_CODE                VARCHAR2(4),
  CODE_ID                VARCHAR2(6)       NOT NULL,
  CODE_ID_NM             VARCHAR2(60),
  CODE_ID_DC             VARCHAR2(200),
  USE_AT                 CHAR(1),
  FRST_REGISTER_PNTTM    DATE             DEFAULT sysdate,
  FRST_REGISTER_ID       VARCHAR2(20),
  LAST_UPDUSR_PNTTM      DATE             DEFAULT sysdate,
  LAST_UPDUSR_ID         VARCHAR2(20),
    CONSTRAINT COMTCCMMNCODE_PK
    PRIMARY KEY ( CODE_ID ),
    FOREIGN KEY ( CL_CODE )
        REFERENCES COMTCCMMNCLCODE ( CL_CODE )
)
;

COMMENT ON TABLE COMTCCMMNCODE IS '공통코드 대분류 관리';

COMMENT ON COLUMN COMTCCMMNCODE.CL_CODE IS '분류코드';

COMMENT ON COLUMN COMTCCMMNCODE.CODE_ID IS '코드ID';

COMMENT ON COLUMN COMTCCMMNCODE.CODE_ID_NM IS '코드ID명';

COMMENT ON COLUMN COMTCCMMNCODE.CODE_ID_DC IS '코드ID 설명';

COMMENT ON COLUMN COMTCCMMNCODE.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTCCMMNCODE.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTCCMMNCODE.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTCCMMNCODE.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTCCMMNCODE.LAST_UPDUSR_ID IS '최종수정자ID';

CREATE TABLE COMTCCMMNDETAILCODE (
  CODE_NM                VARCHAR2(60),
  CODE_DC                VARCHAR2(200),
  USE_AT                 CHAR(1),
  CODE                   VARCHAR2(45)      NOT NULL,
  CODE_ID                VARCHAR2(18)      NOT NULL,
  FRST_REGISTER_PNTTM    DATE             DEFAULT sysdate,
  FRST_REGISTER_ID       VARCHAR2(20),
  LAST_UPDUSR_PNTTM      DATE             DEFAULT sysdate,
  LAST_UPDUSR_ID         VARCHAR2(20),
    CONSTRAINT COMTCCMMNDETAILCODE_PK
    PRIMARY KEY ( CODE_ID, CODE ),
    FOREIGN KEY ( CODE_ID )
        REFERENCES COMTCCMMNCODE ( CODE_ID )
)
;

COMMENT ON TABLE COMTCCMMNDETAILCODE IS '공통코드 상세 관리';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.CODE_NM IS '코드명';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.CODE_DC IS '고드설명';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.CODE IS '코드';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.CODE_ID IS '코드ID';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTCCMMNDETAILCODE.LAST_UPDUSR_ID IS '최종수정자ID';

CREATE TABLE MEMBER (
  ID      VARCHAR2(100)     NOT NULL,
  PWD     VARCHAR2(100)     NOT NULL,
  NAME    VARCHAR2(100),
    PRIMARY KEY ( ID )
)
;

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

CREATE TABLE COMTNEMPLYRSCRTYESTBS (
  SCRTY_ESTBSTRGET_ID    VARCHAR2(20)     NOT NULL,
  MBER_TY_CODE           VARCHAR2(15)     NOT NULL,
  AUTHOR_CODE            VARCHAR2(30)     NOT NULL,
    CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK
    PRIMARY KEY ( SCRTY_ESTBSTRGET_ID, MBER_TY_CODE )
)
;

COMMENT ON TABLE COMTNEMPLYRSCRTYESTBS IS '권한별 메뉴관리[부서권한관리]';

COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.SCRTY_ESTBSTRGET_ID IS '사용자ID';

COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.MBER_TY_CODE IS '사용자구분';

COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.AUTHOR_CODE IS '권한 코드';

CREATE TABLE COMTNROLES_HIERARCHY (
  PARENT_ROLE    VARCHAR2(30)     NOT NULL,
  CHILD_ROLE     VARCHAR2(30)     NOT NULL,
    CONSTRAINT COMTNROLES_HIERARCHY_PK
    PRIMARY KEY ( PARENT_ROLE, CHILD_ROLE )
)
;

COMMENT ON TABLE COMTNROLES_HIERARCHY IS '권한계층';

COMMENT ON COLUMN COMTNROLES_HIERARCHY.PARENT_ROLE IS '부모 롤';

COMMENT ON COLUMN COMTNROLES_HIERARCHY.CHILD_ROLE IS '자식 롤';

CREATE TABLE COMTNMENUCREATDTLS (
  MENU_NO        NUMBER(20)       NOT NULL,
  MAPCREAT_ID    VARCHAR2(35),
  AUTHOR_CODE    VARCHAR2(30)     NOT NULL,
    CONSTRAINT COMTNMENUCREATDTLS_PK
    PRIMARY KEY ( MENU_NO, AUTHOR_CODE )
)
;

COMMENT ON TABLE COMTNMENUCREATDTLS IS '메뉴생성내역';

COMMENT ON COLUMN COMTNMENUCREATDTLS.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN COMTNMENUCREATDTLS.MAPCREAT_ID IS '맵생성ID';

COMMENT ON COLUMN COMTNMENUCREATDTLS.AUTHOR_CODE IS '권한코드';

CREATE TABLE COMTECOPSEQ (
  TABLE_NAME    VARCHAR2(20)     NOT NULL,
  NEXT_ID       NUMBER           NOT NULL,
    CONSTRAINT COMTECOPSEQ_PK
    PRIMARY KEY ( TABLE_NAME )
)
;

COMMENT ON TABLE COMTECOPSEQ IS '시퀀스 처리 테이블';

CREATE TABLE COMTNTMPLATINFO (
  TMPLAT_ID              CHAR(20)           NOT NULL,
  TMPLAT_NM              VARCHAR2(120),
  TMPLAT_COURS           VARCHAR2(2000),
  USE_AT                 CHAR(1)            NOT NULL,
  FRST_REGISTER_ID       VARCHAR2(20)       NOT NULL,
  FRST_REGISTER_PNTTM    DATE               NOT NULL,
  LAST_UPDUSR_ID         VARCHAR2(20),
  LAST_UPDUSR_PNTTM      DATE,
  TMPLAT_SE_CODE         CHAR(6)
)
;

COMMENT ON TABLE COMTNTMPLATINFO IS '템플릿';

COMMENT ON COLUMN COMTNTMPLATINFO.TMPLAT_ID IS '템플릿ID';

COMMENT ON COLUMN COMTNTMPLATINFO.TMPLAT_NM IS '템플릿명';

COMMENT ON COLUMN COMTNTMPLATINFO.TMPLAT_COURS IS '템플릿경로';

COMMENT ON COLUMN COMTNTMPLATINFO.USE_AT IS '사용여부';

COMMENT ON COLUMN COMTNTMPLATINFO.FRST_REGISTER_ID IS '최초등록자ID';

COMMENT ON COLUMN COMTNTMPLATINFO.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN COMTNTMPLATINFO.LAST_UPDUSR_ID IS '최종수정자ID';

COMMENT ON COLUMN COMTNTMPLATINFO.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN COMTNTMPLATINFO.TMPLAT_SE_CODE IS '템플릿구분';

CREATE TABLE COMTNAUTHORINFO (
  AUTHOR_CODE        VARCHAR2(30)      NOT NULL,
  AUTHOR_NM          VARCHAR2(50)      NOT NULL,
  AUTHOR_DC          VARCHAR2(100),
  AUTHOR_CREAT_DE    DATE              NOT NULL,
    CONSTRAINT CONTNAUTHORINFO_PK
    PRIMARY KEY ( AUTHOR_CODE )
)
;

COMMENT ON TABLE COMTNAUTHORINFO IS '권한관리';

COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_CODE IS '권한ID';

COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_NM IS '권한명';

COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_DC IS '권한설명';

COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_CREAT_DE IS '등록일자';

CREATE TABLE COMTN_CONTENTS (
  MENU_NO      NUMBER(20)       NOT NULL,
  CV_NO        NUMBER(20)       NOT NULL,
  CV_CON       CLOB,
  USE_YN       CHAR(1)         DEFAULT 'Y',
  DEL_YN       CHAR(1)         DEFAULT 'N',
  REG_ID       VARCHAR2(64),
  REG_DATE     DATE            DEFAULT sysdate,
  MODI_ID      VARCHAR2(64),
  MODI_DATE    DATE            DEFAULT SYSDATE,
    CONSTRAINT COMTN_CONTENTS_PK
    PRIMARY KEY ( MENU_NO, CV_NO ),
    FOREIGN KEY ( MENU_NO )
        REFERENCES COMTNMENUINFO ( MENU_NO )
)
;

COMMENT ON TABLE COMTN_CONTENTS IS '컨텐츠관리';

COMMENT ON COLUMN COMTN_CONTENTS.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN COMTN_CONTENTS.CV_NO IS '컨텐츠번호';

COMMENT ON COLUMN COMTN_CONTENTS.CV_CON IS '컨텐츠';

COMMENT ON COLUMN COMTN_CONTENTS.USE_YN IS '사용여부';

COMMENT ON COLUMN COMTN_CONTENTS.DEL_YN IS '삭제여부';

COMMENT ON COLUMN COMTN_CONTENTS.REG_ID IS '등록자ID';

COMMENT ON COLUMN COMTN_CONTENTS.REG_DATE IS '등록일';

COMMENT ON COLUMN COMTN_CONTENTS.MODI_ID IS '수정자ID';

COMMENT ON COLUMN COMTN_CONTENTS.MODI_DATE IS '수정일';

CREATE TABLE PORTAL_ALERT (
  ALERT_CD            NUMBER(38)         NOT NULL,
  ALERT_NM            VARCHAR2(1200),
  ALERT_URL           VARCHAR2(4000),
  ATCH_FILE_ID        CHAR(20),
  PUBLISH             CHAR(1),
  POPUP               CHAR(1),
  PUB_SDATE           VARCHAR2(30),
  PUB_EDATE           VARCHAR2(30),
  IS_DEL              CHAR(1),
  REG_USER_ID         VARCHAR2(60),
  LAST_MOD_USER_ID    VARCHAR2(60),
  REG_DT              DATE,
  LAST_MOD_DT         DATE,
  PRIORITY            NUMBER(38),
  CATEGORY            VARCHAR2(12)      DEFAULT '0',
  TYPE                VARCHAR2(6),
  MAP_YN              CHAR(1)
    CONSTRAINT PK_PORTAL_ALERT
    PRIMARY KEY ( ALERT_CD )
)
;

COMMENT ON TABLE PORTAL_ALERT IS '알림';

COMMENT ON COLUMN PORTAL_ALERT.ALERT_CD IS '알림번호';

COMMENT ON COLUMN PORTAL_ALERT.ALERT_NM IS '알림명';

COMMENT ON COLUMN PORTAL_ALERT.ALERT_URL IS '알림URL';

COMMENT ON COLUMN PORTAL_ALERT.ATCH_FILE_ID IS '파일첨부아이디';

COMMENT ON COLUMN PORTAL_ALERT.PUBLISH IS '노출여부';

COMMENT ON COLUMN PORTAL_ALERT.POPUP IS '팝업여부';

COMMENT ON COLUMN PORTAL_ALERT.PUB_SDATE IS '노출시작일';

COMMENT ON COLUMN PORTAL_ALERT.PUB_EDATE IS '노출종료일';

COMMENT ON COLUMN PORTAL_ALERT.IS_DEL IS '삭제여부';

COMMENT ON COLUMN PORTAL_ALERT.REG_USER_ID IS '등록자ID';

COMMENT ON COLUMN PORTAL_ALERT.LAST_MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN PORTAL_ALERT.REG_DT IS '등록일';

COMMENT ON COLUMN PORTAL_ALERT.LAST_MOD_DT IS '수정일';

COMMENT ON COLUMN PORTAL_ALERT.PRIORITY IS '순서';

COMMENT ON COLUMN PORTAL_ALERT.CATEGORY IS '카테고리';

COMMENT ON COLUMN PORTAL_ALERT.TYPE IS '타입';

COMMENT ON COLUMN PORTAL_ALERT.MAP_YN IS 'URL 타입';

CREATE TABLE BANNER (
  BNR_CD              NUMBER(38)         NOT NULL,
  BNR_NM              VARCHAR2(4000),
  BNR_URL             VARCHAR2(500)      NOT NULL,
  DEPT_ID             VARCHAR2(15),
  REG_DT              DATE,
  REG_USER_ID         VARCHAR2(20),
  LAST_MOD_DT         DATE,
  LAST_MOD_USER_ID    VARCHAR2(20),
  IS_DEL              CHAR(1)            NOT NULL,
  PUBLISH             CHAR(1),
  DEPT                VARCHAR2(8),
  DONG                VARCHAR2(8),
  GUBUN               VARCHAR2(2),
  USE_BANNER          VARCHAR2(1000),
  START_DT            VARCHAR2(10),
  END_DT              VARCHAR2(10),
  ORDERLY             NUMBER(38),
  POPUP               CHAR(1)           DEFAULT 'N',
  ATCH_FILE_ID        CHAR(20),
    CONSTRAINT PK_BANNER
    PRIMARY KEY ( BNR_CD )
)
;

COMMENT ON TABLE BANNER IS '배너';

COMMENT ON COLUMN BANNER.BNR_CD IS '번호';

COMMENT ON COLUMN BANNER.BNR_NM IS '배너명';

COMMENT ON COLUMN BANNER.BNR_URL IS '배너URL';

COMMENT ON COLUMN BANNER.DEPT_ID IS '부서아이디';

COMMENT ON COLUMN BANNER.REG_DT IS '등록일';

COMMENT ON COLUMN BANNER.REG_USER_ID IS '등록자ID';

COMMENT ON COLUMN BANNER.LAST_MOD_DT IS '수정일';

COMMENT ON COLUMN BANNER.LAST_MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN BANNER.IS_DEL IS '삭제여부';

COMMENT ON COLUMN BANNER.PUBLISH IS '노출여부';

COMMENT ON COLUMN BANNER.ATCH_FILE_ID IS '파일첨부아이디';

COMMENT ON COLUMN BANNER.DEPT IS '부서';

COMMENT ON COLUMN BANNER.DONG IS '동';

COMMENT ON COLUMN BANNER.GUBUN IS '구분';

COMMENT ON COLUMN BANNER.USE_BANNER IS '사용여부';

COMMENT ON COLUMN BANNER.START_DT IS '시작일';

COMMENT ON COLUMN BANNER.END_DT IS '종료일';

COMMENT ON COLUMN BANNER.ORDERLY IS '순서';

COMMENT ON COLUMN BANNER.POPUP IS '팝업';

DROP TABLE KISTEP.COMTNBBS_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE KISTEP.COMTNBBS_COMMENT (
  CMMNT_ID               NUMBER             NOT NULL,
  BBS_ID                 VARCHAR2(20)       NOT NULL,
  NTT_ID                 NUMBER             NOT NULL,
  NTCR_ID                VARCHAR2(20)           NULL,
  PASSWORD               VARCHAR2(2000)         NULL,
  NTT_CN                 CLOB                   NULL,
  FRST_REGISTER_PNTTM    DATE                   NULL,
  NTCR_NM                VARCHAR2(50)           NULL,
  NTT_SJ                 VARCHAR2(2400)         NULL,
  NTCR_EMAIL             VARCHAR2(100)          NULL,
  RECOMMEND              NUMBER                 NULL,
  DELCODE                CHAR(1)                NULL,
  LAST_UPDUSR_PNTTM      DATE                   NULL,
  NTCR_PINNO             VARCHAR2(70)           NULL,
  GUBUN                  VARCHAR2(100)          NULL,
  OPTION1                VARCHAR2(4000)         NULL,
  OPTION2                VARCHAR2(4000)         NULL,
  OPTION3                VARCHAR2(4000)         NULL
)
TABLESPACE USERS
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE (
    INITIAL 64 K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE KISTEP.COMTNBBS_COMMENT IS '댓글 테이블';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.CMMNT_ID IS '게시물ID';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.BBS_ID IS '게시판ID';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTT_ID IS '부모ID';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTCR_ID IS '게시자ID';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.PASSWORD IS '비밀번호';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTT_CN IS '게시물내용';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.FRST_REGISTER_PNTTM IS '최초등록시점';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTCR_NM IS '게시자명';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTT_SJ IS '게시물제목';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTCR_EMAIL IS '이메일';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.RECOMMEND IS '추천수';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.DELCODE IS '삭제여부';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.LAST_UPDUSR_PNTTM IS '최종수정시점';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.NTCR_PINNO IS '핀번호';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.GUBUN IS '구분(1:HRST ~~)';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.OPTION1 IS '옵션1';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.OPTION2 IS '옵션2';

COMMENT ON COLUMN KISTEP.COMTNBBS_COMMENT.OPTION3 IS '옵션3';

ALTER TABLE KISTEP.COMTNBBS_COMMENT ADD
(
    CONSTRAINT PK_
    PRIMARY KEY ( CMMNT_ID )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64 K
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);

CREATE TABLE SATISFACTION (
  SID          NUMBER(20)         NOT NULL,
  MENU_NO      NUMBER(20)         NOT NULL,
  STATUS       CHAR(1)            	  NULL,
  OPINION      VARCHAR2(2000)         NULL,
  REG_DATE     DATE                   NULL,
  USER_KEY     VARCHAR2(255)          NULL
);

COMMENT ON TABLE SATISFACTION IS '만족도';

COMMENT ON COLUMN SATISFACTION.SID IS '번호';

COMMENT ON COLUMN SATISFACTION.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN SATISFACTION.STATUS IS '만족도값';

COMMENT ON COLUMN SATISFACTION.OPINION IS '의견';

COMMENT ON COLUMN SATISFACTION.REG_DATE IS '등록일';

COMMENT ON COLUMN SATISFACTION.USER_KEY IS '인증키';

ALTER TABLE SATISFACTION ADD
(
    PRIMARY KEY ( SID )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64 K
            NEXT 1024 K
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);



