INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('관리자', 100001, 0, 1, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:09', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('지표관리', 100002, 100001, 1, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('HRST', 100003, 100002, 1, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('RSTI', 100004, 100002, 2, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('RDPS', 100005, 100002, 3, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('ICST', 100006, 100002, 4, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('BIS', 100007, 100002, 5, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('AIM', 100008, 100002, 6, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('출처관리', 100009, 100002, 7, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('게시물관리', 100010, 100001, 2, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('통합게시판관리', 100011, 100010, 1, '', 1, '/bos/bbs/SelectBBSMasterInfs.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('게시판정보관리', 100012, 100011, 1, '', 1, '/bos/bbs/SelectBBSMasterInfs.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('게시판속성', 100013, 100011, 2, '', 1, '/bos/pg/pageAttrList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('공지사항', 100014, 100010, 2, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('FAQ', 100015, 100010, 3, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('Q&A', 100016, 100010, 4, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('자료실', 100017, 100010, 5, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('의견게시판', 100018, 100010, 6, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('사용자관리', 100019, 100001, 3, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:10', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('관리자정보', 100020, 100019, 1, '', 1, '/bos/adminMember/list.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('권한관리', 100021, 100019, 2, '', 1, '/bos/cmm/sec/ram/AuthorList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('권한관리', 100022, 100021, 1, '', 1, '/bos/cmm/sec/ram/AuthorList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('부서권한관리', 100023, 100021, 2, '', 1, '/bos/cmm/sec/ram/DeptAuthorList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('권한별메뉴관리', 100024, 100021, 3, '', 1, '/bos/sym/mpm/MenuCreatManageSelect.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('사이트관리', 100027, 100001, 4, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('코드관리', 100028, 100027, 1, '', 1, '/bos/sym/ccm/ccc/CcmCmmnClCodeList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('공통분류코드관리', 100029, 100028, 1, '', 1, '/bos/sym/ccm/ccc/CcmCmmnClCodeList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('공통코드관리', 100030, 100028, 2, '', 1, '/bos/sym/ccm/cca/CcmCmmnCodeList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('공통상세코드관리', 100031, 100028, 3, '', 1, '/bos/sym/ccm/cde/CcmCmmnDetailCodeList.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('관련사이트', 100032, 100027, 2, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('지표이용통계', 100033, 100027, 3, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('통합검색관리', 100034, 100027, 4, '', 1, '', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('메뉴관리', 100035, 100027, 5, '', 1, '/bos/sym/mpm/MenuListSelect/1.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('관리자메뉴관리', 100036, 100035, 1, '', 1, '/bos/sym/mpm/MenuListSelect/1.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('컨텐츠관리', 100037, 100027, 6, '', 1, '/bos/sym/mpm/commonContents/list/2.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

INSERT INTO comtnmenuinfo
  (MENU_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, SITE_ID, MENU_LINK, MENU_POPUP_YN, DEPT_ID, PATH, FULL_PATH, FULL_MENU_LINK, CONTENTS_PATH, USE_YN, MODIFY_DAY, POSITION, LEAF_NODE_YN, USER_ID, BBS_ID)
VALUES
  ('사이트관리', 100038, 100027, 7, '', 1, '/bos/siteMng/list.do', 'N', '', '', '', '', '', 'Y', to_date('2014-11-24 16:12:11', 'yyyy-mm-dd hh24:mi:ss'), '', '', '', '');

