/* entity code update */
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&#130;',',') WHERE BBS_ID = 'B0000047';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&nbsp;',' ') WHERE BBS_ID = 'B0000047';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&amp;','&') WHERE BBS_ID = 'B0000047';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&lt;','<') WHERE BBS_ID = 'B0000047';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&gt;','>') WHERE BBS_ID = 'B0000047';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&#39;','`') WHERE BBS_ID = 'B0000047';


UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&#91;','[') WHERE BBS_ID = 'B0000020';
UPDATE TB_BBS_ESTN SET NTT_SJ = REPLACE(NTT_SJ,'&#93;',']') WHERE BBS_ID = 'B0000020';



UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#91;','[');
UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#93;',']');
UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#43;','+');
UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#47;','/');
UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#130;',',');

UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#40;','(');
UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#41;',')');

UPDATE TN_EMPMN_PBLANC SET PBLANC_NM = REPLACE(PBLANC_NM,'&#39;','`');
